# Generated by Django 5.1.1 on 2024-09-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kontakt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meno', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('cislo', models.CharField(max_length=13, unique=True)),
            ],
        ),
    ]
